second_mr
tusharkx/test_github pull request #2
Opened 2021-05-17 01:23 UTC by tusharkx

mr to test comments in mr

2021-05-17 05:46 UTC, idf-build requested changes

2021-05-17 05:46 UTC, idf-build commented on foo1.txt
> +fil edited for a pull request
test!

2021-05-17 05:58 UTC, idf-build requested changes
requesting changes

2021-05-17 06:18 UTC, idf-build reviewed
adding comment

2021-05-17 06:19 UTC, idf-build reviewed
adding comment

2021-05-17 06:31 UTC, idf-build reviewed
this is just a comment

2021-05-17 06:32 UTC, idf-build reviewed
this is just a comment

2021-05-17 06:32 UTC, idf-build reviewed
this is just a comment

2021-05-17 06:32 UTC, idf-build reviewed
this is just a comment

2021-05-17 06:33 UTC, tusharkx reviewed
comment through ui

2021-05-17 06:49 UTC, idf-build reviewed
this is a comment

2021-05-17 06:49 UTC, idf-build reviewed
this is a comment

2021-05-17 06:49 UTC, idf-build reviewed
this is a comment

2021-05-17 06:57 UTC, idf-build reviewed
final comment

2021-05-17 07:20 UTC, idf-build commented on foo1.txt
>  another test file
comment added by sys-owrbuild

2021-05-17 08:21 UTC, tusharkx commented on foo1.txt
>  another test file
resolved!

2021-05-17 08:33 UTC, idf-build requested changes
hello

2021-05-26 01:23 UTC, idf-build reviewed
new way to add comment by sys-owrbuild

2021-05-26 01:26 UTC, idf-build reviewed
add comment by sys-owrbuild

2021-05-26 01:28 UTC, idf-build reviewed
add comment by sys-owrbuild

2021-05-26 09:09 UTC, idf-build commented on foo1.txt
> +fil edited for a pull request
comment

2021-05-27 07:56 UTC, merged